version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '02:00'  # Schedule updates at 2 AM UTC
    open-pull-requests-limit: 10  # Reduce open PRs limit for better manageability
    labels:
      - 'dependencies'
    assignees:  # Add assignees or reviewers
      - 'bitpredator'
    commit-message:
      prefix: '[bot]'

  # Dependencies npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '02:00'  # Schedule updates at 2 AM UTC
    open-pull-requests-limit: 10  # Reduce open PRs limit for better manageability
    labels:
      - 'dependencies'
    assignees:  # Add assignees or reviewers
      - 'bitpredator'
    commit-message:
      prefix: '[bot]'
    ignore:
      - dependency-name: 'some-development-dependency'  # Example to ignore specific dependencies
        versions: ['< 1.0.0']